### PR TITLE
Escape snippets in fenced code blocks

### PR DESCRIPTION
**Pull request by jacmoe**
Really dirty hack but this change means that snippets in fenced code blocks are not processed by the plugin.

### CODE REVIEW

**Comment by infostreams** [comment]
Great, thanks! I hadn't considered this use case yet, great addition. I want to merge this as one commit if possible, but if [I do that myself](https://jesse.sh/clean-up-pull-requests-with-git-merge---squash/) I'd lose author information – it would list me as the author instead of you, and I don't want that. Would you mind squashing them into one commit and resubmitting the pull request?

**Comment by infostreams** [comment]
Oh whatever I'll just merge ;-)

**Comment by jacmoe** [comment]
Thanks! :)
I am not using git on a daily basis - Mercurial and Bitbucket FTW! so I would have to learn how to merge two commits - I will learn how now as I see your point. :)
BTW your Phile plugin is awesome - should be shipped with Phile by default.

**Comment by infostreams** [comment]
Too late! I already merged it. It doesn't matter so much. But thanks! It would be great if this plugin would be shipped with Phile by default. I agree wholeheartedly and had been thinking that myself, but if I suggest it that would be a bit overly vain. I'm 100% in favor though.

**Pull request merged**
