### PR TITLE
Make the replaced tags more unique since a simple search replace of b…

### PR DESCRIPTION
**Pull request by jacmoe**
…rackets really isn't a good idea because almost all programming languages uses them from arrays. :p

### CODE REVIEW

**Comment by jacmoe** [comment]
I believe I fixed my fix :)
Very naive of me to think that brackets could be unique.. :p

**Comment by infostreams** [comment]
Nice article! And thanks for mentioning my plugin ;-) I've made some adjustments to the code you submitted and pushed them back to github and released it as a new minor version (1.1.7). Thanks!

**Comment by jacmoe** [comment]
Nice adjustments.
I actually thought about using unique_id or something like it myself but decided against it because I thought it would be overkill. Thanks. :)

**Comment by infostreams** [comment]
Yeah most likely overkill but, on the other hand, it probably doesn't hurt. Many thanks again!

**Pull request merged**
